name: bot
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.6

# Add regular dependencies here.
dependencies:
  args: ^2.0.0
  path: ^1.8.0
  sembast: ^3.0.0
  crypt: ^4.3.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
